language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
env:
  - PERL_DISTRIBUTION_METADATA_DEBUG=1
script:
  - perl -MExtUtils::Packlist -le 'my $e = "ExtUtils::Packlist"; printf STDERR "-----> %s %s\n", $e, $e->VERSION'
  - prove -l t xt
